# Generated by Django 5.0.4 on 2024-07-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='published_date',
        ),
    ]
